# Generated by Django 5.2.1 on 2025-05-29 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmpDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=50)),
                ("managerId", models.IntegerField()),
                ("managaer_Name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="empList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
                ("mobile_number", models.BigIntegerField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("joining_date", models.DateField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Employee.empdepartment",
                    ),
                ),
            ],
        ),
    ]
