# Generated by Django 5.2.1 on 2025-05-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empdepartment",
            old_name="managaer_Name",
            new_name="manager_Name",
        ),
    ]
